// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DynamicParallaxMap","status":true,"description":"Gestiona capas de parallax dinámicas y estáticas en tus mapas.","parameters":{"resolutionX":"1000","resolutionY":"800","extraTiles":"1","ImageSets":"","LimpiezaMapas":"[]"}}
];
